version: '3.1'
services:
  web-service:
    container_name: website
    command: jekyll s --drafts --future --force_polling 
    image: jekyll/jekyll:3.5
    volumes:
      - /opt/site:/srv/jekyll
    expose:
      - 4000
      
networks:
  default:
    external:
      name: nginx_default